<?php 
//define('K_PATH_IMAGES', '/res/img/');
require_once('tcpdf/config/tcpdf_config.php');
require_once('tcpdf/tcpdf.php');
include_once(__DIR__ . "/../PDF.helper.php");
include_once(__DIR__ . "/../Session.helper.php");


session_start();
ob_start();
class PDFClass extends TCPDF{

    //Page header
    public function Header() {

        $imageFile = K_PATH_IMAGES.'redlife-logo.jpg';
        $this->Image($imageFile, 122, 10, "", 15, 'JPG', '', 'C', false, 300, '', false, false, 0, false, false, false);
        $this->SetFont('helvetica', 'B', 20); 
    }

    // Page footer
    public function Footer() {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        // Set font
        $this->SetFont('helvetica', 'I', 8);
        // Page number
        $title = SessionHelper::get("reportID");
        $author = SessionHelper::get("reportAuthor");
        $date = date('D M d Y');
        $this->Write(0, $title. " | Generated by: " . $author . " | ". $date, '', 0, 'C', true, 0, false, false, 0);
    }
}
//new PDFHelper();
$pdf = new PDFClass("L", "mm", "A4", true, 'UTF-8', false);

$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor(SessionHelper::get("reportID"));
$pdf->SetTitle('Report | '. SessionHelper::get("reportID"));
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
$pdf->SetFont('times', '', 12);

$pdf->AddPage();

$IDwithTitle = SessionHelper::get("reportTitle");
$pdf->Write(1, $IDwithTitle, '', 0, 'C', true, 0, false, false, 0);
$pdf->Write(0, "", '', 0, 'C', true, 0, false, false, 0);
$tableData = SessionHelper::get("reportTable");
$table = <<<EOF
        <style>
            table, td, thead {
                border: 1px solid black;
                border-collapse: collapse;
            }
        </style>
        <table>{$tableData}</table>
        EOF;
        
$pdf->writeHTML($table, true, true, true, true, "L");
$pdf->setCellPadding("1");
$pdf->Write(0, "--nothing follows--", '', 0, 'C', true, 0, false, false, 0);
ob_end_clean();
$pdf->Output('admin-report.pdf');


?>